max_epochs: 400
accelerator: gpu
devices: 1
log_every_n_steps: 10
default_root_dir: null # Need to override this in the command line or in the config
check_val_every_n_epoch: 50
enable_checkpointing: true
enable_progress_bar: true
