optimizer_name: AdamW
optimizer_params:
  lr: 0.00005
  betas: [0.9, 0.999]
  weight_decay: 0.1
num_validation_batches_to_sample: 1
num_validation_batches_to_inpaint: 1
num_plot_sample: 1
num_plot_inpaint: 1
inpainting_spatial_name:
  - R_HIP
  - R_KNEE
  - R_ANKLE
  - R_SHOULDER
  - R_ELBOW
  - R_WRIST
inpainting_temporal_interval: [27, 54]
inpainting_camera_index: 0
